### ISSUE TITLE
HTTP server closes connection

### ISSUE THREAD

**Issue by futuretap** [ljalves/hfeasy#1]
I've installed the v3 firmware on my Wifi plug. For whatever reason I can open the /status and /config web pages only in Chrome (on Mac). Neither Safari on Mac, nor Safari on iPhone nor Chrome on iPhone nor a generic HTTP client work. They all complain that the remote side has closed the connection.

However, setting the switch using /state?sw= works fine from all browsers (though a result page is shown in Chrome on Mac, only). Any idea?

**Comment by ljalves** [comment]
The webserver itself is builtin the SDK - not sure if I can do anything about that.
Does the module wifi config webpage have the same issue? (http://ip/)

**Comment by futuretap** [comment]
No that works just fine. Only /config and /status are affected.

**Comment by ljalves** [comment]
Confirmed... installed Safari for windows and it doesn't open those pages... weird!
I'll try to debug it.

Firefox and chrome in windows do work ok...

**Comment by ljalves** [comment]
Fixed on commit ca4d996c4ae90511600d881e4ebae702406b24d5
(available on version 0v4)

**Comment by futuretap** [comment]
Thank you, works great!
