### ISSUE TITLE
How to control dim value on Wall Dimmer (AW51011D) - HF-LPB100

### ISSUE THREAD

**Issue by chaudhryfaisal** [ljalves/hfeasy#13]
Hello, First of all, many thanks for your involvement and development,

I am trying to update AW51011D and it seems to have no impact. I tried to upload *HFEASY0v7_DIMMER_UPGRADE.bin* and after upgrade goes through it present same web page again as if nothing changes. I also tried *ORIGINAL_FW_DIMMER_1_5115.BIN.bin* and it again had no effect on it. 

![Screen Shot 2020-04-06 at 8 51 38 PM](https://user-images.githubusercontent.com/9321772/78621712-dd0fcc80-7848-11ea-90b7-c2f7d997d4af.png)
![Screen Shot 2020-04-06 at 8 51 20 PM](https://user-images.githubusercontent.com/9321772/78621714-dd0fcc80-7848-11ea-95f0-1748c977811c.png)

**Comment by ljalves** [comment]
Did you read the README.md? Main webpage does not change!
After flashing hfeasy just check one of its webpages works (like http://ip/status).

**Comment by chaudhryfaisal** [comment]
yes I thought I updated this post but it was in draft 
I was able to flash it with your firmware. my next question was how to control brightness but I figured it out by invoking state?sw=1-128

thank you again for the amazing work you have done.
