### ISSUE TITLE
CORS header

### ISSUE THREAD

**Issue by mrMikeWatson** [ljalves/hfeasy#18]
Any way to easily add this http header?
Access-Control-Allow-Origin: *

This would allow a simple pretty html page to be built using ajax to toggle relay.

**Comment by ljalves** [comment]
Not sure I understood the idea...
Add that header to which webpage?

You can already control the device at http://ip/ctrl

**Comment by ljalves** [comment]
I read about CORS and I see your idea.
Do you still need this?

**Comment by mrMikeWatson** [comment]
I only have one device that uses this and it is on the shelf right now.
So no rush, and if it is a pain to do, no worries.
Nice work on this greatly enhances the device, appreciated.
