### ISSUE TITLE
hfeasy on rec plug startup mode

### ISSUE THREAD

**Issue by papampi** [ljalves/hfeasy#27]
I just installed hfeasy firmware on rec plug but it boots with state 0 disconnected mode.
Is there any way to make it boot with state 1, connected mode?

Also tried to restore to factory and now the app not work. 
Any ideas?

**Comment by papampi** [comment]
Update:
Found out that if use on timer it will wait the time and turn on the device at reboot.

**Comment by jayPare** [comment]
@papampi do you mean Timer or Countdown?

**Comment by papampi** [comment]
Timer has two modes on and off each one waits the time you set for the other one to kicks in and activate, so if you set timer to "on" with 5 seconds whenever switch off it gets back on in 5 seconds also if lost power or for whatever reason unplug it waits 5 seconds and turn on the switch.

**Comment by jayPare** [comment]
@papampi yeah so you meant Countdown. Timer feature is not yet implemented.

**Comment by papampi** [comment]
No I mean timer
I use it with http://ip/timer

**Comment by ljalves** [comment]
Let me try to provide at the config page a field to specify the power on state.

**Comment by ljalves** [comment]
Feature available on release 0v9 (https://github.com/ljalves/hfeasy/releases/tag/0v9)
